Repository ureca-yoajung/yoajung-admin, pull requests merged in 2025-06, with the labels that each got.

#5 feat: querydsl 초기설정
  build.gradle
  src/main/java/com/ureca/yoajungadmin/config/QueryDslConfig.java
Labels: setting

#12 [feat] 챗봇 통계 집계 배치 기능 추가
  build.gradle
  src/main/java/com/ureca/yoajungadmin/YoajungAdminApplication.java
  src/main/java/com/ureca/yoajungadmin/chatbot/batch/ChatDailyBatch.java
  src/main/java/com/ureca/yoajungadmin/chatbot/batch/ChatMonthlyBatch.java
  src/main/java/com/ureca/yoajungadmin/chatbot/batch/ChatWeeklyBatch.java
  src/main/java/com/ureca/yoajungadmin/chatbot/controller/BatchTestController.java
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatMemory.java
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatStatType.java
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatStatistic.java
  src/main/java/com/ureca/yoajungadmin/chatbot/repository/ChatMemoryRepository.java
  src/main/java/com/ureca/yoajungadmin/chatbot/repository/ChatStatisticRepository.java
  src/main/java/com/ureca/yoajungadmin/chatbot/schedule/ChatSchedule.java
  src/main/resources/application.yml
Labels: enhancement

#23 [feat] 요금제 통계 배치
  build.gradle
  src/main/java/com/ureca/yoajungadmin/chatbot/controller/BatchTestController.java
  src/main/java/com/ureca/yoajungadmin/plan/batch/PlanBatch.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/PlanStatistic.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/enums/PlanCategory.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/PlanRepository.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/PlanStatisticRepository.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/custom/PlanRepositoryCustom.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/custom/PlanRepositoryImpl.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/custom/PopularPlanDto.java
  src/main/java/com/ureca/yoajungadmin/plan/schedule/PlanSchedule.java
  src/main/java/com/ureca/yoajungadmin/user/entity/AgeGroup.java
Labels: enhancement

#26 [refactor] 엔티티 구조 정리 및 필드명 통일
  src/main/java/com/ureca/yoajungadmin/plan/controller/ProductController.java
  src/main/java/com/ureca/yoajungadmin/plan/controller/request/CreateProductRequest.java
  src/main/java/com/ureca/yoajungadmin/plan/controller/request/UpdateProductRequest.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/Product.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/enums/ProductCategory.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/enums/ProductType.java
  src/main/java/com/ureca/yoajungadmin/plan/service/impl/ProductServiceImpl.java
  src/main/java/com/ureca/yoajungadmin/plan/service/response/ProductResponse.java
Labels: refactor

#29 [refactor] 엔티티 컬럼명 카멜케이스로 변경
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatMemory.java
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatStatistic.java
  src/main/java/com/ureca/yoajungadmin/common/BaseTimeEntity.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/Benefit.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/PlanBenefit.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/PlanProduct.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/PlanStatistic.java
  src/main/java/com/ureca/yoajungadmin/plan/entity/Product.java
  src/main/java/com/ureca/yoajungadmin/review/entity/Review.java
  src/main/java/com/ureca/yoajungadmin/review/entity/ReviewLike.java
  src/main/java/com/ureca/yoajungadmin/user/entity/Tendency.java
  src/main/java/com/ureca/yoajungadmin/user/entity/User.java
Labels: refactor

#31 관리자 요금제, 챗봇 통계, 혜택, 상품 관련 페이지 추가
  src/main/java/com/ureca/yoajungadmin/plan/entity/Plan.java
  src/main/java/com/ureca/yoajungadmin/plan/service/impl/PlanServiceImpl.java
  src/main/java/com/ureca/yoajungadmin/plan/service/impl/ProductServiceImpl.java
  src/main/resources/static/benefit/benefitList.html
  src/main/resources/static/benefit/css/benefitList.css
  src/main/resources/static/benefit/js/benefitList.js
  src/main/resources/static/chat/chatStatistics.html
  src/main/resources/static/chat/chatStatisticsTest.html
  src/main/resources/static/chat/css/chatStatistic.css
  src/main/resources/static/chat/js/chatStatistics.js
  src/main/resources/static/plan/benefitTest.html
  src/main/resources/static/plan/css/planList.css
  src/main/resources/static/plan/js/planList.js
  src/main/resources/static/plan/planList.html
  src/main/resources/static/plan/planTest.html
  src/main/resources/static/product/css/productList.css
  src/main/resources/static/product/js/productList.js
  src/main/resources/static/product/productList.html
Labels: enhancement

#35 [feat] 관리자 리뷰 페이지
  src/main/java/com/ureca/yoajungadmin/config/SecurityConfig.java
  src/main/java/com/ureca/yoajungadmin/review/controller/ReviewController.java
  src/main/java/com/ureca/yoajungadmin/review/dto/ReviewAllPageResponse.java
  src/main/java/com/ureca/yoajungadmin/review/dto/ReviewListResponse.java
  src/main/java/com/ureca/yoajungadmin/review/repository/custom/ReviewRepositoryCustom.java
  src/main/java/com/ureca/yoajungadmin/review/repository/custom/ReviewRepositoryImpl.java
  src/main/java/com/ureca/yoajungadmin/review/service/ReviewService.java
  src/main/java/com/ureca/yoajungadmin/review/service/ReviewServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/benefit/benefitList.html
  src/main/resources/static/chat/chatStatistics.html
  src/main/resources/static/plan/planList.html
  src/main/resources/static/product/productList.html
  src/main/resources/static/reviews/css/reviewList.css
  src/main/resources/static/reviews/js/reviewList.js
  src/main/resources/static/reviews/reviewList.html
Labels: enhancement

#41 [feat] 리뷰 css 맞춤
  src/main/resources/static/benefit/benefitList.html
  src/main/resources/static/reviews/css/reviewList.css
  src/main/resources/static/reviews/reviewList.html
Labels: enhancement

#49 [fix] 상품 이미지 경로 렌더링 문제 수정
  src/main/resources/application.yml
  src/main/resources/static/product/js/productList.js
Labels: bug

#51 [feat] 관리자 ai 초기 셋팅
  build.gradle
  src/main/java/com/ureca/yoajungadmin/chatbot/repository/ChatMemoryRepository.java
  src/main/java/com/ureca/yoajungadmin/config/AIConfig.java
  src/main/resources/application.yml
Labels: documentation, help wanted, setting

#55 [feat] 통계 요약 정리
  src/main/java/com/ureca/yoajungadmin/chatbot/controller/ChatStatisticsController.java
  src/main/java/com/ureca/yoajungadmin/chatbot/service/ChatStatisticService.java
  src/main/java/com/ureca/yoajungadmin/chatbot/service/impl/ChatStatisticServiceImpl.java
  src/main/java/com/ureca/yoajungadmin/chatbot/service/response/ChatStatisticsResponse.java
  src/main/java/com/ureca/yoajungadmin/common/RouteController.java
  src/main/java/com/ureca/yoajungadmin/config/SecurityConfig.java
  src/main/java/com/ureca/yoajungadmin/plan/controller/PlanStatisticController.java
  src/main/java/com/ureca/yoajungadmin/plan/service/PlanStatisticService.java
  src/main/java/com/ureca/yoajungadmin/plan/service/impl/PlanStatisticServiceImpl.java
  src/main/java/com/ureca/yoajungadmin/plan/service/response/PlanStatisticInfoResponse.java
  src/main/resources/application.yml
  src/main/resources/prompt/agePrompt.txt
  src/main/resources/prompt/chatPrompt.txt
  src/main/resources/static/chat/chatStatistics.html
  src/main/resources/static/chat/css/chatStatistic.css
  src/main/resources/static/chat/js/chatStatistics.js
  src/main/resources/static/plan/css/planStatistics.css
  src/main/resources/static/plan/js/planStatistics.js
  src/main/resources/static/plan/planStatistics.html
Labels: enhancement, good first issue, help wanted

#57 [feat] 통계 로딩 개선
  src/main/java/com/ureca/yoajungadmin/chatbot/entity/ChatMemory.java
  src/main/resources/static/chat/chatStatistics.html
  src/main/resources/static/chat/css/chatStatistic.css
  src/main/resources/static/chat/js/chatStatistics.js
  src/main/resources/static/plan/css/planStatistics.css
  src/main/resources/static/plan/js/planStatistics.js
  src/main/resources/static/plan/planStatistics.html
Labels: documentation, enhancement

#61 [feat] 요금제 별 리뷰 요약 기능 및 조회 ui
  src/main/java/com/ureca/yoajungadmin/common/BaseCode.java
  src/main/java/com/ureca/yoajungadmin/plan/repository/PlanRepository.java
  src/main/java/com/ureca/yoajungadmin/review/repository/ReviewRepository.java
  src/main/java/com/ureca/yoajungadmin/summary/client/DifyClient.java
  src/main/java/com/ureca/yoajungadmin/summary/client/DifyProperties.java
  src/main/java/com/ureca/yoajungadmin/summary/client/dto/DifyRequest.java
  src/main/java/com/ureca/yoajungadmin/summary/client/dto/DifyResponse.java
  src/main/java/com/ureca/yoajungadmin/summary/controller/PlanSummaryAdminController.java
  src/main/java/com/ureca/yoajungadmin/summary/dto/PlanSummaryDto.java
  src/main/java/com/ureca/yoajungadmin/summary/entity/PlanSummary.java
  src/main/java/com/ureca/yoajungadmin/summary/repository/PlanSummaryRepository.java
  src/main/java/com/ureca/yoajungadmin/summary/scheduler/PlanSummaryScheduler.java
  src/main/java/com/ureca/yoajungadmin/summary/service/PlanSummaryService.java
  src/main/java/com/ureca/yoajungadmin/summary/service/PlanSummaryServiceImpl.java
  src/main/java/com/ureca/yoajungadmin/summary/service/ReviewSamplingService.java
  src/main/java/com/ureca/yoajungadmin/summary/service/ReviewSamplingServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/reviews/css/reviewList.css
  src/main/resources/static/reviews/js/reviewList.js
  src/main/resources/static/reviews/reviewList.html
Labels: enhancement

#71 [feat] 회원가입, 페이지네이션, 요약 재생성 버튼 추가 & 요약 요청 정보 수정
  src/main/java/com/ureca/yoajungadmin/config/SecurityConfig.java
  src/main/java/com/ureca/yoajungadmin/review/repository/ReviewRepository.java
  src/main/java/com/ureca/yoajungadmin/summary/service/PlanSummaryServiceImpl.java
  src/main/resources/static/login.html
  src/main/resources/static/reviews/css/reviewList.css
  src/main/resources/static/reviews/js/reviewList.js
  src/main/resources/static/reviews/reviewList.html
Labels: enhancement

#73 [feat] 전체 요금제 리뷰 요약 기능 (테스트용)
  src/main/java/com/ureca/yoajungadmin/summary/controller/TestController.java
  src/main/java/com/ureca/yoajungadmin/summary/scheduler/PlanSummaryScheduler.java
Labels: enhancement
